name: Travis
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Build:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-18.04
        node-version:
          - 14.x
    steps:
      - name: 'Set up Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v1
        with:
          node-version: '${{ matrix.node-version }}'
      - uses: actions/checkout@v2
      - run: sudo apt-get install -y pandoc jq
      - run: npm install
      - run: npm test
      - run: make
      - run: cp jskos.html gh-pages
      - run: cp context.json gh-pages
      - run: cp schemas/*.json gh-pages
